In [2]:
import pandas as pd

df = pd.DataFrame({
"country": ["USA", "USA", "India", "India"],
"year": [2020, 2021, 2020, 2021],
"sales": [100, 120, 90, 110],
"profit": [20, 25, 18, 22]
})
melted = df.melt(
id_vars=["country", "year"], # columns to keep
value_vars=["sales", "profit"], # columns to unpivot
var_name="metric", # new column name for variable
value_name="value" # new column name for value (default is value)
)
print(melted)

  country  year  metric  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     18
7   India  2021  profit     22

In [3]:
df

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   India  2020     90      18
3   India  2021    110      22

In [9]:
# Merging & Joining
df_customers = pd.DataFrame({
"customer_id": [1, 2, 3, 4],
"name": ["Adam", "Bob", "Charlie", "Dave"]
})
df_orders = pd.DataFrame({
"order_id": [101, 102, 103, 104],
"customer_id": [2, 1, 4, 5],
"amount": [250, 120, 300, 180]
})


pd.merge(df_customers, df_orders, on="customer_id", how="right") # Right Join

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     180